### ISSUE TITLE
[Crash]: Cannot start server-side on 1.20.1, seems to be using client-only code

### ISSUE THREAD

**Issue by SargeRyong** [MattiDragon/AdvancedNetworking#17] opened 2024-04-30 18:49 UTC
### Description of the issue

Started up my Fabric server on 1.20.1 with Advanced Networking 2.0.3.

Produces stack trace, seems to be trying to access something from a client context while running server-side:

[18:38:57] [main/ERROR]: Minecraft has crashed!

...

Caused by: java.lang.**NoSuchFieldError: CLIENT**
        at **io.github.mattidragon.nodeflow.graph.context.ContextType.<clinit>(ContextType.java:41)** ~[nodeflow-0.2.2+mc.1.20.1-98ebe2379b27f61.jar:?]
        at **io.github.mattidragon.advancednetworking.AdvancedNetworking.<clinit>(AdvancedNetworking.java:34)** ~[advanced-networking-2.0.3+mc.1.20.1.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.10.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.10.jar:?]
        at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) ~[supermartijn642corelib-1.1.17-fabric-mc1.20.1.jar:?]
        at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:75) ~[supermartijn642corelib-1.1.17-fabric-mc1.20.1.jar:?]
        at net.minecraft.server.Main.handler$ijd000$supermartijn642corelib$beforeInit(Main.java:3026) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
        ... 4 more

Loads just fine on client side / single player worlds.  Only happens on dedicated server.

### Reproduction steps

1. Start fabric server with advanced networking 2.0.3.
2. Observe stack trace

### Mod version

2.0.3

### Operating System

Linux

### Minecraft version

1.20.1

### Other mods

Fabric API 3.1.4
Sodium 0.5.8
Lithium 0.11.2
Indium 1.0.30

### Server

Happens

### Client

Doesn't happen

### Logs

https://pastebin.com/W98jB1Hn

### Crash Report

https://pastebin.com/W98jB1Hn

**Comment by MattiDragon** [comment] 2024-05-01 06:04
This can be fixed by installing the latest version of nodeflow manually. I've fixed it there, but haven't updated advanced networking to use the fixed version

**Comment by SargeRyong** [comment] 2024-05-02 22:34
Thanks - Is there anyway to manually update and retain compat with MC 1.20.1?

**Comment by MattiDragon** [comment] 2024-08-07 08:26
I've dropped support for 1.20.1 now, and the issue is fixed in later versions

**Closed as not planned by MattiDragon** 2024-08-07 08:26 UTC
Labels: unconfirmed, crash
