### ISSUE TITLE
[Crash]: Client crashes on Fabric 1.21

### ISSUE THREAD

**Issue by Knito58** [MattiDragon/AdvancedNetworking#21] opened 2024-07-30 22:21 UTC
### Description of the issue

Trying to find the somehow missing NBT filter option and messing around with nodes. Probably deleted the "flow" node.

[crash-2024-07-31_00.03.41-client.txt](https://github.com/user-attachments/files/16433967/crash-2024-07-31_00.03.41-client.txt)

Server is unimpressed.

### Reproduction steps

Connect to Server
Do mess around with nodes

### Mod version

V4.0.0. (1.21)

### Operating System

Windows 11 Pro

### Minecraft version

1.21 (Fabric)

### Other mods

Modpack Einseinundzwanzig 1.1.1 is the used modpack but probably no source to that error.

### Server

Happens

### Client

Happens

### Logs

https://pastebin.com/MdRTwAFM

### Crash Report

https://pastebin.com/MdRTwAFM

**Comment by MattiDragon** [comment] 2024-07-31 05:26
I know why this happens. The item capacity node thinks it's an item count node due to a programming error, causing it to try opening the wrong config screen. Restarting the server should convert the broken node to a harmless one.

As a side note: the option to filter by nbt doesn't exist anymore, because item nbt doesn't really exist like it used to. It has been replaced by components, and as such the filtering method has changed. You can find more info about the format by clicking on the link in the filter node.

**Comment by Knito58** [comment] 2024-07-31 06:16
Restarted server. It also used up more memory than usual and is back to normal now. 
(It was on 6gb and now is back to 1.88gb)

As always, I want to filter items with nbt away from extended drawers. The link in the filter node leads to minecraft wiki and installing any of them leads to filter error.

**Comment by MattiDragon** [comment] 2024-07-31 08:18
That memory usage is concerning. If you find a way to reproduce it, please let me know.

I don't think it's really possible to filter for items with changed components. I'd recommend locking your drawers and manually assigning items to them. Then you can use the ordering of split nodes to send everything that doesn't fit elsewhere.

**Comment by Knito58** [comment] 2024-07-31 13:38
Thank you. Made a regex worm which works as whitelist. Same worm as blacklist seems to work only 50% because it also sucks the whitelist-items. Things are cleaned up really quickly and that will not become a new ticket. I'm satisfied with it as it is now. If the crash is fixed then it is good.

**Comment by Knito58** [comment] 2024-08-01 15:31
Just to comfort you: Same worm as blacklist works. Ignore my 50% from above.
I had one hopper too much under the second chest which got that 50%. I can program regex worms but obviously cannot build.

**Closed as completed** 2024-08-20 21:03 UTC
Labels: fixed, confirmed, crash, bug
